server:
  port: 9093

spring:
  profiles:
    active: dev
  application:
    name: USER-INFO
  datasource:
    url: jdbc:mysql://localhost:3306/userdb
    password: root1234
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  mvc:
    pathmatch:
      use-trailing-slash-pattern: false

